### ISSUE TITLE
Убери ip отстуков и проверок)

### ISSUE THREAD

**Issue by webparadoxer** [Lexus2016/broBrowser#1]
Сабж

**Comment by webparadoxer** [comment]
}, "f.vision" !== window.location.hostname.toLowerCase() && (h("toDataURL", HTMLCanvasElement.prototype.toDataURL)
и такие бы вещи убрать

**Comment by Lexus2016** [comment]
Спасибо.

1. Ип оставлен, что бы можно было собрать и проверить работоспособность - он будет отключен через месяц. Никаких отстуков привата нет, никакого сбора информации нет - удаленные запросы для получения информации о стране, временной зоне, языках. Еще была мысль делать АПИ ключи для платной версии - они не используются. 
2. Проверки по домену в коде плагина добавил  специально для будущих ментейнеров , как указания на проблемные участки требующие исправлений.

Никаких исправлений вносить не могу по договоренности с новыми владельцами- все выложено как есть.
